"""
Minimal subset of PlaceOrder/analysis/pattern_scan.py -- only the two helper
functions swing20_screener.py actually needs (add_extra_momentum,
forward_window), extracted so this clean project doesn't have to also carry
pattern_scan.py's own heavy dependency chain (target_1to1_5mo_10to15pct.py ->
live_screener.py -> ...), which isn't used at all by the swing20 model.
"""
import os
import numpy as np
import pandas as pd


PRICE_COLS_TO_ADJUST = ("CLOSE_PRICE", "HIGH_PRICE", "LOW_PRICE", "OPEN_PRICE", "PREV_CLOSE")


def apply_cached_split_adjustments(bhav):
    """Load and apply pre-computed split adjustments from cache CSV (if it exists).
    Cache is generated by adjust_splits_batch.py and refreshed ~monthly.
    Zero network calls, just CSV reads -- fast path for factor calculation.
    Scales every OHLC/prev-close column present (not just Close) -- scaling Close
    alone left High/Low/Open/PrevClose on the pre-split scale, which corrupts any
    ratio between them (day_range_pct, close_strength, gap_pct) for the ~20-45
    sessions after a split, for rows before its ex-date."""
    cache_file = os.path.join(os.path.dirname(__file__), "split_adjustments_cache.csv")
    if not os.path.exists(cache_file):
        return bhav  # no cache yet
    
    try:
        cache = pd.read_csv(cache_file)
        if cache.empty:
            return bhav
        
        bhav = bhav.copy()
        for _, row in cache.iterrows():
            symbol = row["SYMBOL"]
            ex_date = pd.Timestamp(row["ex_date"])
            ratio = float(row["adjustment_ratio"])
            
            sym_mask = bhav["SYMBOL"] == symbol
            pre_ex_mask = sym_mask & (bhav["DATE1"] < ex_date)
            for col in PRICE_COLS_TO_ADJUST:
                if col in bhav.columns:
                    bhav.loc[pre_ex_mask, col] = bhav.loc[pre_ex_mask, col] * ratio
        
        return bhav
    except Exception:
        return bhav  # on any error, return unadjusted

def add_extra_momentum(df, bench_close):
    g = df.groupby("SYMBOL", group_keys=False)
    df["ret_10"] = g["CLOSE_PRICE"].transform(lambda s: s.pct_change(10))
    df["ret_20"] = g["CLOSE_PRICE"].transform(lambda s: s.pct_change(20))
    df["ret_40"] = g["CLOSE_PRICE"].transform(lambda s: s.pct_change(40))
    df["rs_20"] = df["ret_20"] - df["DATE1"].map(bench_close.pct_change(20))
    df["rs_40"] = df["ret_40"] - df["DATE1"].map(bench_close.pct_change(40))
    return df


def forward_window(df, day_min, day_max):
    """Vectorized close-only max/min/final % return over sessions day_min..day_max
    ahead of each row, per symbol (no stop-loss -- pure buy-and-hold resolution)."""
    g = df.groupby("SYMBOL", group_keys=False)

    def fwd(s):
        arr = s.values
        n = len(arr)
        max_ret = np.full(n, np.nan)
        min_ret = np.full(n, np.nan)
        final_ret = np.full(n, np.nan)
        for i in range(n):
            start, end = i + day_min, i + day_max + 1
            if start >= n:
                continue
            window = arr[start:end]
            if len(window) == 0:
                continue
            rel = window / arr[i] - 1
            max_ret[i], min_ret[i], final_ret[i] = rel.max(), rel.min(), rel[-1]
        return pd.DataFrame({"fwd_max": max_ret, "fwd_min": min_ret, "fwd_final": final_ret}, index=s.index)

    out = g["CLOSE_PRICE"].apply(fwd)
    out.index = out.index.droplevel(0) if isinstance(out.index, pd.MultiIndex) else out.index
    return out["fwd_max"], out["fwd_min"], out["fwd_final"]
